#!/bin/sh
iptables -I INPUT -p tcp -m multiport --dport %s --syn -j DROP
sleep 0.2
/usr/sbin/haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -sf $(cat /var/run/haproxy.pid)
iptables -D INPUT -p tcp -m multiport --dport %s --syn -j DROP
